# Generated by Django 4.0.4 on 2022-04-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_product_product_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
