# Generated by Django 4.0.4 on 2022-04-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
