# Generated by Django 4.0.4 on 2022-04-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
