# Generated by Django 4.0.4 on 2022-04-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
